name: GuardRails

on: [push]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: installing the node
        uses: actions/setup-node@v1
        with: 
          node-version: "14.x"
      - name: running the tests
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: GuardRails-APIs.postman_collection.json