name: GuardRails

on: [push]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: installing the node
        uses: actions/setup-node@v1
        with: 
          node-version: "14.x"
      - name: installing newman
        run: |
          npm install -g newman
      - name: Running the tests
        run: newman run ../../GuardRails-APIs.postman_collection.json