name: GuardRails

on: [push]

jobs:
  newman-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install newman
        run: |
          npm install -g newman
      - name: Run the tests
        run: newman run GuardRails-APIs.postman_collection.json
